import type { Config } from "tailwindcss";

// All values below are taken directly from the Stitch-generated DESIGN.md
// ("Technical Precision" design system) so the real app matches the
// approved mockups pixel-for-pixel.
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#39393c",
        "surface-container-lowest": "#0e0e11",
        "on-surface-variant": "#c8c5ca",
        "on-surface": "#e4e1e5",
        "on-primary": "#313032",
        "surface-container-highest": "#353437",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1b1b1e",
        "surface-tint": "#c8c6c8",
        "primary-container": "#09090b",
        "surface-container-high": "#2a2a2d",
        "tertiary-fixed-dim": "#adc6ff",
        "on-tertiary-container": "#2875e8",
        primary: "#c8c6c8",
        "secondary-fixed": "#6ffbbe",
        "inverse-surface": "#e4e1e5",
        "on-secondary-fixed": "#002113",
        "on-background": "#e4e1e5",
        "error-container": "#93000a",
        "tertiary-container": "#00081e",
        surface: "#131316",
        "on-tertiary": "#002e6a",
        "secondary-container": "#00a572",
        "on-tertiary-fixed-variant": "#004395",
        "primary-fixed": "#e5e1e4",
        "on-secondary-fixed-variant": "#005236",
        "outline-variant": "#47464a",
        "on-secondary": "#003824",
        outline: "#919095",
        "surface-container": "#1f1f22",
        "surface-dim": "#131316",
        tertiary: "#adc6ff",
        "on-primary-container": "#7a787b",
        "inverse-on-surface": "#303033",
        "secondary-fixed-dim": "#4edea3",
        "on-error": "#690005",
        "on-secondary-container": "#00311f",
        "inverse-primary": "#5f5e60",
        "on-primary-fixed": "#1c1b1d",
        "on-primary-fixed-variant": "#474649",
        "tertiary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#c8c6c8",
        "surface-variant": "#353437",
        "on-tertiary-fixed": "#001a42",
        secondary: "#4edea3",
        error: "#ffb4ab",
        background: "#131316",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2.5rem",
        gutter: "24px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md-mobile": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "mono-metric": ["JetBrains Mono", "monospace"],
        "mono-label": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "mono-metric": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "mono-label": ["13px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
